version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.dockerfile
    ports:
      - "8099:80"
    volumes:
      - ./:/var/www/Prof2
    links:
      - fpm
  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.dockerfile
    volumes:
      - ./:/var/www/Prof2
    links:
      - mysql1
  mysql1:
    image: mysql:5.7
    ports:
      - 33062:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=profiles
    volumes:
    - my-datavolume:/var/lib/mysql1
volumes:
  my-datavolume:
